from typing import Any, Callable, Iterable, Optional, Sequence, Union
import numpy as np
from numpy.typing import NDArray

# How an index is described to the factory and the runner:
#
#     ("lattice", "SELECT")
#     ("expression", "[a-zA-Z_][a-zA-Z0-9_]*")
#     ("group", include_id, [exclude_id, ...])
#
# A group names its members by id, so a group may hold other groups.
IndexSpec = Union[
    tuple[str, str],
    tuple[str, int, Sequence[int]],
]

# Called when a head reaches the end of its index, with its id, the payload it
# was spawned with, and what it matched. Returns `None` at the end of the graph,
# or the `(spec, payload)` pairs of the indexes that may follow.
Resolver = Callable[[int, Any, str], Optional[Sequence[tuple[IndexSpec, Any]]]]

class BooleanPolynomialRing:
    """Boolean polynomials over `GF(2)[t..]/(t^2 - t)`, as decision diagrams.

    A polynomial is the `int` id of a node in this ring's diagram; the diagram
    is hash consed, so equal ids mean equal polynomials, and `0` is the zero
    polynomial and `1` the constant one.
    """

    def __init__(self, names: Sequence[str]) -> None: ...
    def one(self) -> int: ...
    def zero(self) -> int: ...
    def mutual_exclusion(self, names: Sequence[str]) -> int: ...
    def product(self, left: int, right: int) -> int: ...
    def sum(self, left: int, right: int) -> int: ...
    def is_zero(self, poly: int) -> bool: ...
    def assume(self, poly: int, name: str) -> int: ...
    def constrained(self, poly: int) -> frozenset[str]: ...
    def holds_empty(self, poly: int) -> bool: ...
    def nonzero(self, poly: int, others: Sequence[int]) -> list[bool]: ...
    def viable(self, poly: int) -> frozenset[str]: ...
    def render(self, poly: int) -> str: ...
    def term_count(self, poly: int) -> int: ...
    def node_count(self) -> int: ...
    def memory_usage(self) -> int: ...

class Multigraph:
    """An undirected multigraph whose only mutation is vertex contraction.

    Vertices come from the edges alone, and labels are opaque. `copy` shares
    both the edges and the contraction state, so a branch that is copied,
    queried and dropped allocates nothing.
    """

    def __init__(self, edges: Optional[Iterable[tuple[str, str, Any]]] = None) -> None: ...
    def copy(self) -> Multigraph: ...
    def __contains__(self, node: str) -> bool: ...
    def __len__(self) -> int: ...
    def nodes(self) -> list[str]: ...
    def edges(self, node: str) -> list[tuple[str, Any]]: ...
    def merge_vertices(self, head: str, other: str) -> bool: ...
    def edge_count(self) -> int: ...
    def memory_usage(self) -> int: ...
    def base_memory_usage(self) -> int: ...

class Vocabulary:
    def __init__(self, data: bytes, eos_id: int) -> None: ...
    @classmethod
    def from_file_path(cls, file_path: str, eos_id: int) -> Vocabulary: ...
    def get_token_by_id(self, id: int) -> Optional[str]: ...
    def get_id_by_token(self, token: str) -> Optional[int]: ...
    def get_eos_id(self) -> int: ...
    def get_tokens(self) -> list[str]: ...
    def get_ids(self) -> list[int]: ...
    def get_token_by_idx(self, idx: int) -> Optional[str]: ...
    def get_id_by_idx(self, idx: int) -> Optional[int]: ...

class AhoCorasick:
    @staticmethod
    def new(vocabulary: Vocabulary) -> AhoCorasick: ...

class Lattice:
    def __init__(self, input: str, vocabulary: Vocabulary, ac_base: AhoCorasick) -> None: ...
    def transitions(self, node_id: int) -> NDArray[np.uint64]: ...
    def next(self, node_id: int, token_id: int) -> Optional[int]: ...
    def accepting(self, node_id: int) -> Optional[bool]: ...
    def node_count(self) -> int: ...
    def memory_usage(self) -> int: ...

class TokTrie:
    @staticmethod
    def new(vocabulary: Vocabulary) -> TokTrie: ...

class Expression:
    def __init__(self, input: str, vocabulary: Vocabulary, toktrie_base: TokTrie) -> None: ...
    def transitions(self, node_id: int) -> NDArray[np.uint64]: ...
    def next(self, node_id: int, token_id: int) -> Optional[int]: ...
    def accepting(self, node_id: int) -> Optional[bool]: ...
    def node_count(self) -> int: ...
    def memory_usage(self) -> int: ...

class Factory:
    """The index registry: drafts in, ids out.

    Indexes are kept here rather than handed back, so one index backs every
    head that needs it, and a spec is built at most once however many threads
    ask for it at the same moment.
    """

    def __init__(self, vocabulary: Vocabulary, cache: bool = True) -> None: ...
    @staticmethod
    def with_bases(
        vocabulary: Vocabulary,
        ac_base: AhoCorasick,
        trie_base: TokTrie,
        cache: bool = True,
    ) -> Factory: ...
    def fork(self, cache: bool = True) -> Factory: ...
    def create(self, spec: IndexSpec) -> Optional[int]: ...
    def create_many(self, specs: Iterable[IndexSpec]) -> list[Optional[int]]: ...
    def lattice(self, word: str) -> Optional[int]: ...
    def expression(self, pattern: str) -> Optional[int]: ...
    def group(self, include: int, excludes: Sequence[int]) -> Optional[int]: ...
    def is_cached(self, spec: IndexSpec) -> bool: ...
    def label(self, index_id: int) -> str: ...
    def node_count(self, index_id: int) -> int: ...
    def memory_usage(self, index_id: int) -> int: ...
    def is_group(self, index_id: int) -> bool: ...
    def __len__(self) -> int: ...
    @property
    def builds(self) -> int: ...

class Head:
    """A snapshot of one active index. The live state stays in the kernel."""

    @property
    def id(self) -> int: ...
    @property
    def index_id(self) -> int: ...
    @property
    def node(self) -> int: ...
    @property
    def rule(self) -> str: ...
    @property
    def matched(self) -> str: ...
    @property
    def payload(self) -> Any: ...

class Runner:
    """The pool of active indexes, and the workers that drive them.

    Set a resolver, spawn the heads to start from, then feed tokens. Each token
    is fed to every head across the worker pool; a head that reaches the end of
    its index is reported to the resolver, and the indexes it answers with are
    built on the same workers and become the next heads.
    """

    def __init__(self, factory: Factory, workers: int = 0) -> None: ...
    def set_resolver(self, callback: Resolver) -> None: ...
    def spawn(self, spec: Union[IndexSpec, int], payload: Any) -> Optional[int]: ...
    def spawn_many(self, items: Iterable[tuple[IndexSpec, Any]]) -> list[int]: ...
    def feed(self, token_id: int) -> bool: ...
    def settle(self) -> None: ...
    def routes(self) -> NDArray[np.uint64]: ...
    def heads(self) -> list[Head]: ...
    def head(self, head_id: int) -> Optional[Head]: ...
    def kill(self, head_id: int) -> bool: ...
    def clear(self) -> None: ...
    def is_completed(self) -> bool: ...
    def matched(self) -> str: ...
    def __len__(self) -> int: ...
    @property
    def factory(self) -> Factory: ...
    @property
    def workers(self) -> int: ...
    @property
    def stats(self) -> tuple[int, int, int]: ...
