import numpy as np
import numpy.typing as npt

def init_vocabulary(data: bytes, eos_id: int) -> int: ...
def init_schema(data: bytes) -> int: ...
def routes() -> npt.NDArray[np.uint32]: ...
def feed(token_id: int) -> int: ...
def get_token(token_id: int) -> str | None: ...
def get_token_id(token: str) -> int | None: ...
