from typing import Optional
import numpy as np
from numpy.typing import NDArray

FAST_HASH_DFA: int
DOUBLE_HASH_DFA: int
FLAT_DFA: int

AC_CONTIGUOUS_NFA: int
AC_NONCONTIGUOUS_NFA: int
AC_DFA: int

class Vocabulary:
    def __init__(self, data: bytes, eos_id: int, t_size: int) -> None: ...
    @classmethod
    def from_file_path(cls, file_path: str, eos_id: int, t_size: int) -> Vocabulary: ...
    def get_token_by_id(self, id: int) -> Optional[str]: ...
    def get_id_by_token(self, token: str) -> Optional[int]: ...
    def get_eos_id(self) -> int: ...

class AhoCorasick:
    @staticmethod
    def new(vocabulary: Vocabulary, kind: int) -> AhoCorasick: ...

class Lattice:
    def __init__(self, input: str, vocabulary: Vocabulary, ac_base: AhoCorasick) -> None: ...
    def start(self) -> int: ...
    def transitions(self, node_id: int) -> NDArray[np.uint64]: ...
    def next(self, node_id: int, token_id: int) -> Optional[int]: ...
    def node_count(self) -> int: ...
    def memory_usage(self) -> int: ...

class TokTrie:
    @staticmethod
    def new(vocabulary: Vocabulary, dfa_type: int, n_size: int, t_size: int) -> TokTrie: ...

class Expression:
    def __init__(self, input: str, vocabulary: Vocabulary, toktrie_base: TokTrie) -> None: ...
    def start(self) -> int: ...
    def transitions(self, node_id: int) -> NDArray[np.uint64]: ...
    def next(self, node_id: int, token_id: int) -> Optional[int]: ...
    def node_count(self) -> int: ...
    def memory_usage(self) -> int: ...
