from typing import Optional
import numpy as np
from numpy.typing import NDArray

class Vocabulary:
    def __init__(self, data: bytes, eos_id: int) -> None: ...
    @classmethod
    def from_file_path(cls, file_path: str, eos_id: int) -> Vocabulary: ...
    def get_token_by_id(self, id: int) -> Optional[str]: ...
    def get_id_by_token(self, token: str) -> Optional[int]: ...
    def get_eos_id(self) -> int: ...
    def get_tokens(self) -> list[str]: ...
    def get_ids(self) -> list[int]: ...
    def get_token_by_idx(self, idx: int) -> Optional[str]: ...
    def get_id_by_idx(self, idx: int) -> Optional[int]: ...

class AhoCorasick:
    @staticmethod
    def new(vocabulary: Vocabulary) -> AhoCorasick: ...

class Lattice:
    def __init__(self, input: str, vocabulary: Vocabulary, ac_base: AhoCorasick) -> None: ...
    def transitions(self, node_id: int) -> NDArray[np.uint64]: ...
    def next(self, node_id: int, token_id: int) -> Optional[int]: ...
    def accepting(self, node_id: int) -> Optional[bool]: ...
    def node_count(self) -> int: ...
    def memory_usage(self) -> int: ...

class TokTrie:
    @staticmethod
    def new(vocabulary: Vocabulary) -> TokTrie: ...

class Expression:
    def __init__(self, input: str, vocabulary: Vocabulary, toktrie_base: TokTrie) -> None: ...
    def transitions(self, node_id: int) -> NDArray[np.uint64]: ...
    def next(self, node_id: int, token_id: int) -> Optional[int]: ...
    def accepting(self, node_id: int) -> Optional[bool]: ...
    def node_count(self) -> int: ...
    def memory_usage(self) -> int: ...
